services:
  builder:
    network_mode: host
    container_name: builder
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/fyralabs/fyra-build-client:main
    privileged: true

    restart: unless-stopped
    volumes:
      - cache:/var/cache
      - /tmp:/tmp
    env_file:
      - .env
      - .env.auth
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  cache:
  tailscale:
