services:
  sccache-server:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/fyralabs/fyra-build-client:main
    privileged: true

    restart: unless-stopped
    volumes:
      - cache:/var/cache
      - /tmp:/tmp
    env_file:
      - .env
    environment:
      - SCCACHE_LOG=trace

  # tailscale:
  #   container_name: tailscale
  #   network_mode: host
  #   privileged: true
  #   image: tailscale/tailscale:latest
  #   restart: always
  #   volumes:
  #     - tailscale:/var/lib/tailscale
  #     - /tmp/tailscale:/tmp

  #   env_file:
  #     - .env
  #   environment:
  #     - TS_STATE_DIR=/var/lib/tailscale

volumes:
  cache:
  tailscale:
